#!/bin/bash

type module 1>/dev/null 2>/dev/null
if [ $? -ne 0 ]
then
	modulecmd_exe=$(which modulecmd)
	if [ $? -ne 0 ]
	then
		echo "Error: Neither Lmod nor Environment Modules could be detected."
		echo "Exiting."
		exit 1
	else
		function module () 
		{ 
			eval `"${modulecmd_exe}" bash $*`
		}
	fi
fi

home_dir=$(eval echo ~)
output_file="${home_dir}/modules-$$.txt"

rm -rf "${output_file}"

badmods=( )

for mod in $(module avail -t 2>&1 | grep -v ':$')
do
	print_this_module=true
	for badmod in ${badmods[*]}
	do
		if [ "${mod}" == "${badmod}" ]
		then
			print_this_module=false
			break
		fi
	done
	if [ "${print_this_module}" == "true" ]
	then	
		module whatis $mod 2>&1
	fi
done | \
	sed -e 's/:\s\+Description:/:/' | \
	grep ': ' | \
	grep -v ":ERROR:" | \
	grep -Ev "[Nn]ot (supported|available)" | \
	grep -v "only available" | \
	sed -e '/^\s*$/d' \
	> "${output_file}"
